Repository teamOpener/OpenOff-Client, pull requests merged in 2023-10, with the labels that each got.

#148 feat: 회원가입 번호 인증화면 제거
  src/constants/authorize/join.ts
  src/navigators/AuthorizeNavigator.tsx
  src/screens/authorize/joins/AgreeToTermScreen/AgreeToTermScreen.tsx
  src/screens/authorize/joins/EmailPasswordScreen/EmailPasswordScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
  src/types/apps/menu.ts
  src/types/join.ts
Labels: ✨ feat, 🌈 enhancement

#151 fix: xcode 15 build error 해결
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/react-native-vision-camera+2.15.5.patch
Labels: 🐛 bug

#154 🌈 enhancement: 애플로그인에 핸드폰번호 스킵기능 추가
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
Labels: 🌈 enhancement

#156 feat: 회원탈퇴 api 추가
  src/apis/user.ts
  src/hooks/queries/user.ts
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
Labels: ✨ feat

#158 feat: 로그인 프로세스 전체 개선
  src/apis/index.ts
  src/components/eventDetail/atoms/comments/CommentInput/CommentInput.tsx
  src/components/eventDetail/atoms/comments/ParentCommentListItem/ParentCommentListItem.tsx
  src/components/home/buttons/BookmarkButton/BookmarkButton.tsx
  src/components/home/floatingbutton/FloatingButton.tsx
  src/components/user/buttons/UserProfileImageButton/UserProfileImageButton.tsx
  src/components/user/groups/UserSupportGroup/UserSupportGroup.tsx
  src/containers/home/PersonalEventContainer.tsx
  src/containers/user/UserInfoContainer/UserInfoContainer.style.ts
  src/containers/user/UserInfoContainer/UserInfoContainer.tsx
  src/containers/user/UserNeedToLoginContainer/UserNeedToLoginContainer.style.ts
  src/containers/user/UserNeedToLoginContainer/UserNeedToLoginContainer.tsx
  src/containers/userEvent/HostEventContainer.tsx
  src/containers/userEvent/HostNeedToLoginContainer/HostNeedToLoginContainer.style.ts
  src/containers/userEvent/HostNeedToLoginContainer/HostNeedToLoginContainer.tsx
  src/containers/userEvent/ParticipationEventContainer.tsx
  src/containers/userEvent/ParticipationNeedToLoginContainer/ParticipationNeedToLoginContainer.style.ts
  src/containers/userEvent/ParticipationNeedToLoginContainer/ParticipationNeedToLoginContainer.tsx
  src/hooks/queries/user.ts
  src/locales/en.json
  src/locales/ko.json
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/screens/authorize/joins/AgreeToTermScreen/AgreeToTermScreen.tsx
  src/screens/authorize/joins/EmailPasswordScreen/EmailPasswordScreen.tsx
  src/screens/authorize/joins/InterestFieldScreen/InterestFieldScreen.tsx
  src/screens/authorize/joins/JoinCompleteScreen/JoinCompleteScreen.tsx
  src/screens/authorize/joins/NickNameScreen/NickNameScreen.tsx
  src/screens/authorize/joins/PhoneCertificationScreen/PhoneCertificationScreen.tsx
  src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/screens/events/EventApplyScreen/EventApplyScreen.tsx
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/user/UserInterestResetScreen/UserInterestResetScreen.tsx
  src/screens/user/UserPasswordResetScreen/UserPasswordResetScreen.tsx
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
  src/screens/user/UserScreen/UserScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.style.ts
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/types/apps/menu.ts
  src/types/declarations.d.ts
Labels: 🌈 enhancement
