Repository teamOpener/OpenOff-Client, pull requests merged in 2023-07, with the labels that each got.

#25 feat: ios env 파일 설정
  .gitignore
  ios/Config.xcconfig
  ios/OpenOff-Bridging-Header.h
  ios/OpenOff.xcodeproj/project.pbxproj
  ios/OpenOff.xcodeproj/xcshareddata/xcschemes/OpenOff.xcscheme
  ios/OpenOff/AppDelegate.mm
  ios/OpenOff/Info.plist
  ios/Podfile.lock
  ios/SwiftBridge.swift
Labels: ✨ feat

#39 이벤트맵 추가기능 구현
  src/components/eventMap/buttons/CurrentFindButton/CurrentFindButton.tsx
  src/components/eventMap/cards/MapEventCard/MapEventCard.style.ts
  src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
  src/components/eventMap/dialogs/SortDialog/SortDialog.style.ts
  src/components/eventMap/dialogs/SortDialog/SortDialog.tsx
  src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.style.ts
  src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.tsx
  src/components/eventMap/inputs/EventSearchInput/EventSearchInput.tsx
  src/components/eventMap/maps/EventMarker/EventMarker.tsx
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.style.ts
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.tsx
  src/constants/menu.ts
  src/data/lists/eventList.ts
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/navigators/Navigator.tsx
  src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.style.ts
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/eventMap/FieldEventMapScreen/FieldEventMapScreen.tsx
  src/stores/EventMap.ts
  src/stores/app.ts
  src/types/apps/map.ts
  src/types/apps/menu.ts
  src/utils/permission.ts
Labels: ✨ feat, 🫧refactor

#48 text, textinput default props 설정
  App.tsx
  src/components/openEvent/atoms/OpenEvent.style.ts
Labels: 🐛 bug, 💅 design

#50 🔀 디버깅 툴 설치
  App.tsx
  ios/Podfile.lock
  package.json
  src/apis/test.ts
  src/constants/queryKeys.ts
  src/hooks/queries/event.ts
  src/mocks/event/detailEventInfoData.json
  src/models/event/EventComment.ts
  src/models/event/entity/ExtraQuestionInfo.ts
  src/models/event/entity/FieldType.ts
  src/models/event/entity/ImageUrlList.ts
  src/models/event/request/CreateNewEventRequestDto.ts
  src/models/event/response/DetailEventInfoResponseDto.ts
  src/models/event/response/EventIndexStatisticsDto.ts
  yarn.lock
Labels: ✨ feat

#47 Permission 파일 위치 변경 및 알림리스트 화면 구현
  src/assets/icons/IconAlertComment.svg
  src/assets/icons/IconMegaPhone.svg
  src/assets/icons/index.ts
  src/components/home/cards/AlertCard/AlertCard.style.ts
  src/components/home/cards/AlertCard/AlertCard.tsx
  src/components/home/cards/EventRowCard/EventRowCard.stories.tsx
  src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.tsx
  src/components/openEvent/atoms/ImageButton/ImageButton.tsx
  src/constants/code.ts
  src/constants/menu.ts
  src/constants/openEvent/fieldData.ts
  src/data/lists/fieldData.ts
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/hooks/openEvent/useField.ts
  src/mocks/lists/advertisementList.ts
  src/mocks/lists/alertList.ts
  src/mocks/lists/eventList.ts
  src/models/alert/AlertType.ts
  src/models/alert/response/SelectUserAlertResponse.Dto.ts
  src/navigators/Navigator.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/home/AlertScreen/AlertScreen.style.ts
  src/screens/home/AlertScreen/AlertScreen.tsx
  src/screens/home/CategoryEventScreen/CategoryEventScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/home/PopularEventScreen/PopularEventScreen.tsx
  src/screens/home/WishEventScreen/WishEventScreen.tsx
  src/services/permission.ts
  src/types/apps/group.ts
  src/types/apps/menu.ts
  src/types/openEvent/EventForm.ts
Labels: 🐛 bug, ✨ feat, 🫧refactor
