Repository teamOpener/OpenOff-Client, pull requests merged in 2023-08, with the labels that each got.

#52 🔀 이벤트 상세 페이지 제작 (1/2)
  App.tsx
  ios/Podfile.lock
  package.json
  src/assets/icons/IconCalendar.svg
  src/components/common/FixedButton/FixedButton.tsx
  src/components/common/HeadText/HeadText.style.ts
  src/components/common/HeadText/HeadText.tsx
  src/components/common/Image/Image.tsx
  src/components/eventDetail/atoms/DateCard/DateCard.style.ts
  src/components/eventDetail/atoms/DateCard/DateCard.tsx
  src/components/eventDetail/atoms/DateCard/DateCardCarousel.style.ts
  src/components/eventDetail/atoms/DateCard/DateCardCarousel.tsx
  src/components/eventDetail/atoms/PosterCarousel/PosterCarousel.style.ts
  src/components/eventDetail/atoms/PosterCarousel/PosterCarousel.tsx
  src/components/eventDetail/atoms/Tab/Tab.tsx
  src/components/eventDetail/atoms/Tab/TabItem.style.ts
  src/components/eventDetail/atoms/Tab/TabItem.tsx
  src/components/eventDetail/atoms/TitleText/TitleText.style.ts
  src/components/eventDetail/atoms/TitleText/TitleText.tsx
  src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.style.ts
  src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.tsx
  src/components/eventDetail/atoms/buttons/TextButton/TextButton.tsx
  src/components/eventDetail/atoms/index.ts
  src/components/eventDetail/atoms/lists/DefaultSimpleList/DefaultSimpleList.style.ts
  src/components/eventDetail/atoms/lists/DefaultSimpleList/DefaultSimpleList.tsx
  src/components/eventDetail/atoms/lists/SmallSimpleList/SmallSimpleList.style.ts
  src/components/eventDetail/atoms/lists/SmallSimpleList/SmallSimpleList.tsx
  src/components/eventDetail/index.ts
  src/components/eventDetail/layout/ScreenLayout.style.ts
  src/components/eventDetail/layout/ScreenLayout.tsx
  src/components/home/lists/EventCardList/EventCardList.tsx
  src/components/layout/Space/SpaceLayout.tsx
  src/components/openEvent/atoms/Header/Header.tsx
  src/components/openEvent/atoms/index.ts
  src/constants/eventDetail/eventDetailConstants.ts
  src/constants/eventDetail/eventDetailMessage.ts
  src/constants/menu.ts
  src/hooks/queries/event.ts
  src/mocks/event/detailEventInfoData.json
  src/navigators/Navigator.tsx
  src/screens/events/EventApplyScreen/EventApplyScreen.style.ts
  src/screens/events/EventApplyScreen/EventApplyScreen.tsx
  src/screens/events/EventDetailScreen/EventDetailScreen.style.ts
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/screens/events/EventSelectScreen/EventSelectScreen.style.ts
  src/screens/events/EventSelectScreen/EventSelectScreen.tsx
  src/screens/home/OpenEventScreen/OpenEventScreen.tsx
  src/types/apps/menu.ts
  yarn.lock
Labels: ✨ feat, 💅 design

#55 Success & Validate Dialog 제작(1/2)
  App.tsx
  src/components/common/Dialog/Dialog.stories.tsx
  src/components/common/Dialog/Dialog.style.ts
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Dialog/DialogProvider.tsx
  src/hooks/app/useDialog.tsx
  src/navigators/BottomTabNavigator.stories.tsx
  src/screens/authorize/joins/InterestFieldScreen/InterestFieldScreen.stories.tsx
  src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.stories.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/types/apps/dialog.ts
  src/utils/DialogContext.tsx
Labels: ✨ feat, 💅 design

#58 🔀 내 이벤트 참여 페이지 제작
  src/apis/test.ts
  src/assets/icons/IconArrowDown.svg
  src/assets/icons/IconArrowRight.svg
  src/assets/icons/IconArrowUp.svg
  src/assets/icons/IconQR.svg
  src/assets/icons/IconTicketCircle.svg
  src/assets/icons/IconTicketCircles.svg
  src/assets/icons/IconTicketHeart.svg
  src/assets/icons/IconTicketStar.svg
  src/assets/icons/index.ts
  src/components/eventMap/buttons/SelectBoxButton/SelectBoxButton.style.ts
  src/components/eventMap/buttons/SelectBoxButton/SelectBoxButton.tsx
  src/components/navigator/ExitButton/ExitButton.style.ts
  src/components/navigator/ExitButton/ExitButton.tsx
  src/components/userEvent/participant/CategorySelector/CategorySelector.style.ts
  src/components/userEvent/participant/CategorySelector/CategorySelector.tsx
  src/components/userEvent/participant/StatusButton/StatusButton.style.ts
  src/components/userEvent/participant/StatusButton/StatusButton.tsx
  src/components/userEvent/participant/Tab/Tab.tsx
  src/components/userEvent/participant/Tab/TabItem.style.ts
  src/components/userEvent/participant/Tab/TabItem.tsx
  src/components/userEvent/participant/Tag/Tag.style.ts
  src/components/userEvent/participant/Tag/Tag.tsx
  src/components/userEvent/participant/Tag/TagGroup.style.ts
  src/components/userEvent/participant/Tag/TagGroup.tsx
  src/components/userEvent/participant/TicketCard/TicketCard.style.ts
  src/components/userEvent/participant/TicketCard/TicketCard.tsx
  src/components/userEvent/participant/TicketList/TicketList.style.ts
  src/components/userEvent/participant/TicketList/TicketList.tsx
  src/components/userEvent/participant/TicketQR/TicketQR.style.ts
  src/components/userEvent/participant/TicketQR/TicketQR.tsx
  src/components/userEvent/participant/XSmallTag/XSmallTag.style.ts
  src/components/userEvent/participant/XSmallTag/XSmallTag.tsx
  src/components/userEvent/participant/index.ts
  src/constants/code.ts
  src/constants/menu.ts
  src/constants/queryKeys.ts
  src/constants/userEvent/participant/fieldData.ts
  src/constants/userEvent/participant/participantConstants.ts
  src/constants/userEvent/participant/participantMessage.ts
  src/hooks/queries/ledger.ts
  src/mocks/ledger/user/ApplicationInfoResponseData.json
  src/mocks/ledger/user/MyTicketInfoResponseData.json
  src/models/ledger/entity/TicketType.ts
  src/models/ledger/response/ApplicationInfoResponseDto.ts
  src/models/ledger/response/MyTicketInfoResponseDto.ts
  src/navigators/BottomTabNavigator.tsx
  src/navigators/Navigator.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.style.ts
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/screens/userEvent/UserQRScreen/UserQRScreen.style.ts
  src/screens/userEvent/UserQRScreen/UserQRScreen.tsx
  src/screens/userEvent/UserTicketScreen/UserTicketScreen.style.ts
  src/screens/userEvent/UserTicketScreen/UserTicketScreen.tsx
  src/styles/theme.ts
  src/types/apps/menu.ts
  src/types/event/filedDataType.ts
  src/utils/address.ts
  src/utils/date.ts
Labels: ✨ feat, 💅 design

#68 🔀 주최자 콘솔, QR 스캔 기능 제작
  android/build.gradle
  babel.config.js
  ios/Podfile.lock
  package.json
  src/assets/icons/IconBellLing.svg
  src/assets/icons/IconCommentCircle.svg
  src/assets/icons/IconPencilCircle.svg
  src/assets/icons/IconPeople.svg
  src/assets/icons/IconScan.svg
  src/assets/icons/IconStopCircle.svg
  src/assets/icons/index.ts
  src/assets/images/QRBackground.png
  src/components/common/FixedButton/FixedButton.tsx
  src/components/userEvent/host/DateSelector/DateSelector.style.ts
  src/components/userEvent/host/DateSelector/DateSelector.tsx
  src/components/userEvent/host/DonutChart/DonutChart.stories.tsx
  src/components/userEvent/host/DonutChart/DonutChart.tsx
  src/components/userEvent/host/DonutChart/DonutChartInfo.style.ts
  src/components/userEvent/host/DonutChart/DonutChartInfo.tsx
  src/components/userEvent/host/buttons/LargeIconButton/LargeIconButton.style.ts
  src/components/userEvent/host/buttons/LargeIconButton/LargeIconButton.tsx
  src/components/userEvent/host/buttons/SmallIconButton/SmallIconButton.style.ts
  src/components/userEvent/host/buttons/SmallIconButton/SmallIconButton.tsx
  src/components/userEvent/host/index.ts
  src/components/userEvent/host/layout/ConsoleScreenLayout/ConsoleScreenLayout.style.ts
  src/components/userEvent/host/layout/ConsoleScreenLayout/ConsoleScreenLayout.tsx
  src/components/userEvent/host/layout/index.ts
  src/constants/menu.ts
  src/constants/userEvent/host/hostConstants.ts
  src/constants/userEvent/host/hostMessage.ts
  src/hooks/navigator/useRouteParams.ts
  src/navigators/Navigator.tsx
  src/screens/userEvent/HostAlarmScreen/HostAlarmScreen.style.ts
  src/screens/userEvent/HostAlarmScreen/HostAlarmScreen.tsx
  src/screens/userEvent/HostConsoleScreen/HostConsole.style.ts
  src/screens/userEvent/HostConsoleScreen/HostConsoleScreen.tsx
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.style.ts
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
  src/screens/userEvent/HostQRScanScreen/HostQRScanScreen.style.ts
  src/screens/userEvent/HostQRScanScreen/HostQRScanScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/types/apps/menu.ts
  yarn.lock
Labels: ✨ feat, 💅 design

#70 🔀 마이페이지 퍼블리싱 작업
  .ondevice/storybook.requires.js
  src/assets/icons/IconArrowRight.svg
  src/assets/icons/IconVoidTicket.svg
  src/assets/icons/index.ts
  src/components/home/cards/EventCard/EventCard.style.ts
  src/components/home/cards/EventCard/EventCard.tsx
  src/components/user/boxes/UserFieldBox/UserFieldBox.style.ts
  src/components/user/boxes/UserFieldBox/UserFieldBox.tsx
  src/components/user/cards/UserCommentCard/UserCommentCard.style.ts
  src/components/user/cards/UserCommentCard/UserCommentCard.tsx
  src/components/user/groups/UserFieldBoxGroup/UserFieldBoxGroup.style.ts
  src/components/user/groups/UserFieldBoxGroup/UserFieldBoxGroup.tsx
  src/components/user/groups/UserMenuButtonGroup/UserMenuButtonGroup.style.ts
  src/components/user/groups/UserMenuButtonGroup/UserMenuButtonGroup.tsx
  src/components/user/texts/UserInfoText/UserInfoText.style.ts
  src/components/user/texts/UserInfoText/UserInfoText.tsx
  src/mocks/user/userComment.ts
  src/mocks/user/userInfo.ts
  src/screens/user/ScrapScreen/ScrapScreen.stories.tsx
  src/screens/user/ScrapScreen/ScrapScreen.style.ts
  src/screens/user/ScrapScreen/ScrapScreen.tsx
  src/screens/user/UserCommentScreen/UserCommentScreen.stories.tsx
  src/screens/user/UserCommentScreen/UserCommentScreen.style.ts
  src/screens/user/UserCommentScreen/UserCommentScreen.tsx
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.stories.tsx
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.style.ts
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
  src/screens/user/UserScreen/UserScreen.style.ts
  src/screens/user/UserScreen/UserScreen.tsx
  src/styles/textStyles.tsx
  src/types/apps/comment.ts
Labels: ✨ feat, 💅 design

#67 🔀 지도화면 개선
  src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
  src/components/eventMap/groups/SelectBoxGroup/SelectBoxGroup.tsx
  src/components/eventMap/groups/SelectDetailGroup/SelectDetailGroup.tsx
  src/components/eventMap/maps/EventMarker/EventMarker.tsx
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.tsx
  src/hooks/eventMap/useEventMapSelector.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/types/apps/menu.ts
Labels: 🫧refactor, 💅 design

#72 🔀 api 세팅
  App.tsx
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/components/fallback/FallbackError.style.ts
  src/components/fallback/FallbackError.tsx
  src/components/suspense/loading/CommonLoading/CommonLoading.style.ts
  src/components/suspense/loading/CommonLoading/CommonLoading.tsx
  src/hooks/queries/auth.ts
  src/models/auth/request/NormalSignInRequestDto.ts
  src/models/auth/response/TokenResponseDto.ts
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/types/ApiResponse.ts
  src/types/declarations.d.ts
  yarn.lock
Labels: ✨ feat

#76 🔀 이벤트 명단 페이지 (1/2)
  src/apis/eventInstance.ts
  src/apis/ledger.ts
  src/assets/icons/IconFemale.svg
  src/assets/icons/IconMale.svg
  src/assets/icons/index.ts
  src/components/layout/EmptyLayout/EmptyLayout.style.ts
  src/components/layout/EmptyLayout/EmptyLayout.tsx
  src/components/userEvent/host/DateSelector/DateSelector.tsx
  src/components/userEvent/host/IconText/IconText.style.ts
  src/components/userEvent/host/IconText/IconText.tsx
  src/components/userEvent/host/LedgerHeader/LedgerHeader.style.ts
  src/components/userEvent/host/LedgerHeader/LedgerHeader.tsx
  src/components/userEvent/host/SelectBottomSheet/SelectBottomSheet.style.ts
  src/components/userEvent/host/SelectBottomSheet/SelectBottomSheet.tsx
  src/components/userEvent/host/SelectBottomSheet/SortOption.style.ts
  src/components/userEvent/host/SelectBottomSheet/SortOption.tsx
  src/components/userEvent/host/UserCard/UserCard.style.ts
  src/components/userEvent/host/UserCard/UserCard.tsx
  src/components/userEvent/host/UserHeader/UserHeader.style.ts
  src/components/userEvent/host/UserHeader/UserHeader.tsx
  src/components/userEvent/host/buttons/ActionButton/ActionButton.style.ts
  src/components/userEvent/host/buttons/ActionButton/ActionButton.tsx
  src/components/userEvent/host/index.ts
  src/components/userEvent/host/layout/LedgerScreenLayout/LedgerScreenLayout.style.ts
  src/components/userEvent/host/layout/LedgerScreenLayout/LedgerScreenLayout.tsx
  src/components/userEvent/host/layout/index.ts
  src/components/userEvent/participant/TicketList/TicketList.tsx
  src/constants/errorMessage.ts
  src/constants/menu.ts
  src/constants/queryKeys.ts
  src/constants/userEvent/host/hostMessage.ts
  src/hooks/ledger/useBottomSheet.ts
  src/hooks/queries/event.ts
  src/hooks/queries/ledger.ts
  src/mocks/ledger/user/EventLadgerTotalStatusResponseData.json
  src/models/ledger/entity/EventIndexInfo.ts
  src/models/ledger/entity/SortType.ts
  src/models/ledger/request/EventAllApplicantPermitRequestDto.ts
  src/models/ledger/request/EventApplicantInfoRequestDto.ts
  src/models/ledger/request/EventApplicantPermitRequestDto.ts
  src/models/ledger/request/EventLadgerTotalStatusRequestDto.ts
  src/models/ledger/request/HostEventInfoRequestDto.ts
  src/models/ledger/response/EventApplicantInfoResponseDto.ts
  src/models/ledger/response/EventLadgerTotalStatusResponseDto.ts
  src/models/ledger/response/HostEventInfoResponseDto.ts
  src/navigators/Navigator.tsx
  src/screens/userEvent/HostConsoleScreen/HostConsoleScreen.tsx
  src/screens/userEvent/HostLedgerDetailScreen/HostLedgerDetailScreen.style.ts
  src/screens/userEvent/HostLedgerDetailScreen/HostLedgerDetailScreen.tsx
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.style.ts
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.style.ts
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/styles/theme.ts
  src/types/ApiResponse.ts
  src/types/apps/menu.ts
Labels: ✨ feat, 💅 design

#80 🔀 fcm 패키지 설치 및 디바이스 토큰 발급 로직 추가
  .gitignore
  android/app/build.gradle
  android/build.gradle
  index.js
  ios/OpenOff.xcodeproj/project.pbxproj
  ios/OpenOff/AppDelegate.mm
  ios/OpenOff/Info.plist
  ios/OpenOff/OpenOff.entitlements
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/services/fcm.ts
  src/services/permission.ts
  yarn.lock
Labels: ✨ feat

#87 🔀 dialog context 오류 해결
  App.tsx
  src/components/common/dialogs/ConfirmDialog/ConfirmDialog.tsx
  src/components/common/dialogs/Dialog/Dialog.tsx
  src/components/common/dialogs/DialogContext.ts
  src/components/common/dialogs/DialogPortalProvider.tsx
  src/components/common/dialogs/DialogProvider.tsx
  src/components/common/dialogs/DialogProviders.tsx
  src/components/home/cards/EventRowCard/EventRowCard.tsx
  src/hooks/app/useDialog.ts
  src/hooks/app/useDialog.tsx
  src/screens/authorize/finds/EmailFindScreen/EmailFindScreen.tsx
  src/screens/authorize/finds/PasswordFindScreen/PasswordFindScreen.tsx
  src/screens/authorize/finds/PasswordResetScreen/PasswordResetScreen.tsx
  src/screens/authorize/joins/EmailPasswordScreen/EmailPasswordScreen.tsx
  src/screens/authorize/joins/NickNameScreen/NickNameScreen.tsx
  src/screens/authorize/joins/PhoneCertificationScreen/PhoneCertificationScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/types/apps/dialog.ts
Labels: 🐛 bug

#93 🔀 이벤트 개설 페이지 api 연동 (2/2)
  src/apis/user.ts
  src/components/navigator/BackEventButton.tsx
  src/components/openEvent/atoms/DateTimePicker/DateTimePicker.tsx
  src/components/openEvent/atoms/ImageButton/ImageButton.tsx
  src/components/openEvent/atoms/NameTag/NameTag.style.ts
  src/components/openEvent/atoms/NameTag/NameTag.tsx
  src/components/openEvent/atoms/NickNameList/NickNameList.style.ts
  src/components/openEvent/atoms/NickNameList/NickNameList.tsx
  src/components/openEvent/atoms/Tag/Tag.style.ts
  src/components/openEvent/atoms/index.ts
  src/components/openEvent/forms/AdditionalInfo/AdditionalInfo.tsx
  src/components/openEvent/forms/Address/Address.tsx
  src/components/openEvent/forms/Cost/Cost.style.ts
  src/components/openEvent/forms/Cost/Cost.tsx
  src/components/openEvent/forms/Description/Description.tsx
  src/components/openEvent/forms/Period/Period.tsx
  src/components/openEvent/forms/RecruitmentNumber/RecruitmentNumber.tsx
  src/components/openEvent/forms/SubHost/SubHost.style.ts
  src/components/openEvent/forms/SubHost/SubHost.tsx
  src/components/openEvent/forms/Title/Title.tsx
  src/components/openEvent/forms/index.ts
  src/constants/errorMessage.ts
  src/constants/openEvent/openEventConstants.ts
  src/constants/queryKeys.ts
  src/hooks/app/useExitConfirmation.ts
  src/hooks/openEvent/useImageUpload.ts
  src/hooks/queries/event.ts
  src/hooks/queries/user.ts
  src/models/user/request/SearchNicknameRequestDto.ts
  src/models/user/response/SearchNicknameResponseDto.ts
  src/screens/home/OpenEventScreen/OpenEventScreen.style.ts
  src/screens/home/OpenEventScreen/OpenEventScreen.tsx
  src/stores/OpenEventStore.ts
  src/types/openEvent/EventForm.ts
  src/types/openEvent/EventFormError.ts
  src/utils/common.ts
  src/utils/openEvent.ts
Labels: ✨ feat, 💅 design

#94 🔀 이벤트 신청 페이지 api 연동
  src/apis/ledger.ts
  src/components/eventDetail/atoms/DateCard/DateCardCarousel.tsx
  src/components/eventDetail/atoms/EventCalendar/EventCalendar.tsx
  src/components/eventDetail/atoms/QuestionInput/QuestionInput.style.ts
  src/components/eventDetail/atoms/QuestionInput/QuestionInput.tsx
  src/components/eventDetail/atoms/Tab/TabItem.style.ts
  src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.style.ts
  src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.tsx
  src/components/eventDetail/atoms/index.ts
  src/components/home/buttons/BookmarkButton/BookmarkButton.tsx
  src/constants/eventDetail/eventDetailMessage.ts
  src/hooks/event/useEventIndexList.ts
  src/hooks/event/useQnaList.ts
  src/hooks/queries/event.ts
  src/hooks/queries/ledger.ts
  src/models/event/response/DetailEventInfoResponseDto.ts
  src/models/ledger/entity/AnswerInfo.ts
  src/models/ledger/request/ApplyEventRequestDto.ts
  src/models/ledger/response/EventLadgerTotalStatusResponseDto.ts
  src/screens/events/EventApplyScreen/EventApplyScreen.tsx
  src/screens/events/EventDetailScreen/EventDetailScreen.style.ts
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/screens/events/EventSelectScreen/EventSelectScreen.tsx
  src/screens/userEvent/HostConsoleScreen/HostConsoleScreen.tsx
  src/types/apps/menu.ts
  src/types/event/QnaTuple.ts
Labels: ✨ feat, 💅 design

#92 🔀 FCM 토큰 저장방식 개선 및 리플래시 토큰 호출 개선
  ios/Podfile.lock
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/user.ts
  src/models/user/request/UserFcmTokenUploadRequestDto.ts
  src/services/fcm.ts
  src/stores/Authorize.ts
  src/types/apps/asyncAuthorizeStorage.ts
  yarn.lock
Labels: 🐛 bug

#96 🔀 애플로그인 구현
  ios/OpenOff/OpenOff.entitlements
  ios/Podfile.lock
  package.json
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  yarn.lock
Labels: ✨ feat

#99 🔀 이벤트 지도 API 적용
  src/apis/eventInstance.ts
  src/components/common/EmptyScreen/EmptyScreen.tsx
  src/components/eventMap/buttons/CurrentFieldFindButton/CurrentFieldFindButton.style.ts
  src/components/eventMap/buttons/CurrentFieldFindButton/CurrentFieldFindButton.tsx
  src/components/eventMap/buttons/MyCoordinateButton/MyCoordinateButton.style.ts
  src/components/eventMap/cards/MapEventCard/MapEventCard.style.ts
  src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
  src/components/eventMap/groups/SelectBoxGroup/SelectBoxGroup.tsx
  src/components/eventMap/groups/SelectDetailGroup/SelectDetailGroup.tsx
  src/components/eventMap/inputs/EventSearchInput/EventSearchInput.style.ts
  src/components/eventMap/inputs/EventSearchInput/EventSearchInput.tsx
  src/components/eventMap/maps/CurrentMarker/CurrentMarker.tsx
  src/components/eventMap/maps/EventMarker/EventMarker.tsx
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.style.ts
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.tsx
  src/components/home/cards/EventRowCard/EventRowCard.tsx
  src/components/home/lists/BookmarkCardList/BookmarkCardList.style.ts
  src/components/home/lists/BookmarkCardList/BookmarkCardList.tsx
  src/components/home/lists/EventRowCardList/EventRowCardList.style.ts
  src/components/home/lists/EventRowCardList/EventRowCardList.tsx
  src/components/suspense/skeleton/MapEventCardSkeleton/MapEventCardSkeleton.style.ts
  src/constants/queryKeys.ts
  src/constants/selectBox.ts
  src/data/selectData.ts
  src/hooks/eventMap/useEventListFormatter.tsx
  src/hooks/eventMap/useEventMapSelector.tsx
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/hooks/queries/event.ts
  src/models/event/request/EventSearchRequestDto.ts
  src/models/event/response/SearchMapEventInfoResponseDto.ts
  src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/stores/EventMap.ts
  src/types/apps/selectbox.ts
  src/types/event.ts
  src/utils/coordinate.ts
Labels: 🐛 bug, ✨ feat, 💅 design

#105 🔀 기획 수정 & 누락된 UI 구현
  src/assets/icons/IconFourCircle.svg
  src/assets/icons/IconShuriken.svg
  src/assets/icons/IconSnow.svg
  src/assets/icons/index.ts
  src/assets/images/recentLogin.png
  src/components/authorize/buttons/SocialLoginButton/SocialLoginButton.style.ts
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.style.ts
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.tsx
  src/components/authorize/inputs/FormPasswordInput/FormPasswordInput.style.ts
  src/components/authorize/inputs/FormPasswordInput/FormPasswordInput.tsx
  src/components/authorize/texts/ErrorText/ErrorText.tsx
  src/components/home/buttons/BookmarkButton/BookmarkButton.tsx
  src/components/home/cards/CarouselCard/CarouselCard.tsx
  src/components/home/cards/EventRowCard/EventRowCard.tsx
  src/components/home/carousels/AdvertisementCarousel/AdvertisementCarousel.tsx
  src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.style.ts
  src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.tsx
  src/components/home/lists/BookmarkCardList/BookmarkCardList.tsx
  src/components/home/lists/EventCardList/EventCardList.style.ts
  src/components/home/lists/EventCardList/EventCardList.tsx
  src/components/user/groups/UserFieldBoxGroup/UserFieldBoxGroup.style.ts
  src/components/user/groups/UserMenuButtonGroup/UserMenuButtonGroup.tsx
  src/hooks/queries/bookmark.ts
  src/hooks/queries/event.ts
  src/models/user/response/UserTotalInfoResponseDto.ts
  src/screens/authorize/finds/PasswordResetScreen/PasswordResetScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.style.ts
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/user/ScrapScreen/ScrapScreen.tsx
  src/screens/user/UserPasswordResetScreen/UserPasswordResetScreen.tsx
  src/screens/user/UserScreen/UserScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/stores/Authorize.ts
  src/types/event.ts
  src/types/join.ts
  src/types/user.ts
Labels: 🐛 bug, ✨ feat, 💅 design

#107 🔀 댓글/문의하기 제작
  src/apis/comment.ts
  src/assets/icons/IconMore.svg
  src/assets/icons/IconReply.svg
  src/assets/icons/IconSiren.svg
  src/assets/icons/index.ts
  src/components/eventDetail/atoms/comments/ChildCommentListItem/ChildCommentListItem.style.ts
  src/components/eventDetail/atoms/comments/ChildCommentListItem/ChildCommentListItem.tsx
  src/components/eventDetail/atoms/comments/CommentInput/CommentInput.style.ts
  src/components/eventDetail/atoms/comments/CommentInput/CommentInput.tsx
  src/components/eventDetail/atoms/comments/CommentList/CommentList.style.ts
  src/components/eventDetail/atoms/comments/CommentList/CommentList.tsx
  src/components/eventDetail/atoms/comments/DeclarationButton/DeclarationButton.style.ts
  src/components/eventDetail/atoms/comments/DeclarationButton/DeclarationButton.tsx
  src/components/eventDetail/atoms/comments/ParentCommentListItem/ParentCommentListItem.style.ts
  src/components/eventDetail/atoms/comments/ParentCommentListItem/ParentCommentListItem.tsx
  src/components/eventDetail/atoms/index.ts
  src/components/eventDetail/layout/ScreenLayout.tsx
  src/components/suspense/skeleton/CommentRowSkeleton/CommentRowSkeleton.style.ts
  src/components/suspense/skeleton/CommentRowSkeleton/CommentRowSkeleton.tsx
  src/constants/menu.ts
  src/constants/queryKeys.ts
  src/hooks/app/usePullToRefresh.ts
  src/hooks/queries/comment.ts
  src/models/comment/request/ChildCommentInfoRequestDto.ts
  src/models/comment/request/ChildCommentWriteRequestDto.ts
  src/models/comment/request/CommentReportRequestDto.ts
  src/models/comment/request/ParentCommentInfoRequestDto.ts
  src/models/comment/request/ParentCommentWriteRequestDto.ts
  src/models/comment/response/ChildCommentInfoResponseDto.ts
  src/models/comment/response/ChildCommentWriteResponseDto.ts
  src/models/comment/response/ParentCommentInfoResponseDto.ts
  src/models/comment/response/ParentCommentWriteResponseDto.ts
  src/navigators/Navigator.tsx
  src/screens/events/EventCommentScreen/EventCommentScreen.style.ts
  src/screens/events/EventCommentScreen/EventCommentScreen.tsx
  src/screens/events/EventDetailScreen/EventDetailScreen.style.ts
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/types/apps/menu.ts
Labels: ✨ feat, 💅 design

#108 🔀 회원가입시 생일선택 이슈 & 시스템 설정기능 추가 & 지도이슈 수정
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/opener/ExternalURLModule.java
  android/app/src/main/java/com/opener/MyAppPackage.java
  android/app/src/main/java/com/opener/openoff/MainActivity.java
  android/app/src/main/java/com/opener/openoff/MainApplication.java
  android/app/src/main/res/drawable/ic_notification.png
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  package.json
  src/assets/icons/IconApple.svg
  src/assets/icons/index.ts
  src/assets/images/apple.png
  src/components/authorize/buttons/CheckButton/CheckButton.style.ts
  src/components/authorize/buttons/CheckButton/CheckButton.tsx
  src/components/authorize/buttons/SocialLoginButton/SocialLoginButton.style.ts
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.tsx
  src/components/authorize/inputs/BaseInfoInput/BaseInfoInput.tsx
  src/components/authorize/inputs/BirthSettingInput/BirthSettingInput.style.ts
  src/components/authorize/inputs/BirthSettingInput/BirthSettingInput.tsx
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/hooks/queries/user.ts
  src/models/user/request/UserFcmTokenUploadRequestDto.ts
  src/screens/authorize/joins/AgreeToTermScreen/AgreeToTermScreen.tsx
  src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.stories.tsx
  src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.style.ts
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
  src/screens/user/UserScreen/UserScreen.tsx
  src/services/fcm.ts
  src/stores/Authorize.ts
  src/utils/validate.ts
  yarn.lock
Labels: 🐛 bug, ✨ feat, 💅 design

#111 🔀 쿼리 초기화 추가 & 지도 디버깅
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.style.ts
  src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.tsx
  src/components/eventMap/maps/EventMarker/EventMarker.tsx
  src/components/user/groups/UserSupportGroup/UserSupportGroup.style.ts
  src/components/user/groups/UserSupportGroup/UserSupportGroup.tsx
  src/constants/user/userConstants.ts
  src/hooks/eventMap/useEventMapSelector.tsx
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/hooks/queries/event.ts
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/user/UserScreen/UserScreen.style.ts
  src/screens/user/UserScreen/UserScreen.tsx
Labels: 🐛 bug, ✨ feat

#112 🔀 주최자 페이지 보완
  src/apis/ledger.ts
  src/components/common/dialogs/ConfirmDialog/ConfirmDialog.style.ts
  src/components/common/dialogs/ConfirmDialog/ConfirmDialog.tsx
  src/components/common/dialogs/DialogContext.ts
  src/components/common/dialogs/DialogProviders.tsx
  src/components/suspense/loading/ListLoading/ListLoading.tsx
  src/components/userEvent/host/UserCard/UserCard.tsx
  src/components/userEvent/host/UserHeader/UserHeader.tsx
  src/constants/queries/resetQueryKey.ts
  src/constants/queryKeys.ts
  src/hooks/queries/ledger.ts
  src/hooks/queries/useResetQueries.ts
  src/models/ledger/request/EventApplicantInfoRequestDto.ts
  src/models/ledger/request/EventApplicationDenyRequestDto.ts
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.style.ts
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/screens/userEvent/UserTicketScreen/UserTicketScreen.tsx
  src/types/apps/dialog.ts
  src/types/event/DenyEventReason.ts
Labels: 🐛 bug, ✨ feat

#114 🔀 배너 화면 API 적용
  src/apis/banner.ts
  src/components/home/cards/CarouselCard/CarouselCard.tsx
  src/components/home/carousels/AdvertisementCarousel/AdvertisementCarousel.tsx
  src/constants/queryKeys.ts
  src/hooks/queries/banner.ts
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/types/apps/advertisement.ts
Labels: ✨ feat

#116 🔀 UI 일부 수정
  ios/OpenOff/Info.plist
  src/components/home/cards/CarouselCard/CarouselCard.style.ts
  src/components/home/cards/CarouselCard/CarouselCard.tsx
  src/components/openEvent/layout/ScreenLayout.style.ts
  src/components/openEvent/layout/ScreenLayout.tsx
  src/mocks/event/detailEventInfoData.json
  src/mocks/ledger/user/ApplicationInfoResponseData.json
  src/mocks/ledger/user/EventLadgerTotalStatusResponseData.json
  src/mocks/ledger/user/MyTicketInfoResponseData.json
  src/mocks/lists/advertisementList.ts
  src/mocks/lists/alertList.ts
  src/mocks/lists/eventList.ts
  src/mocks/user/userComment.ts
  src/mocks/user/userInfo.ts
  src/screens/home/AlertScreen/AlertScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/home/OpenEventScreen/OpenEventScreen.tsx
  src/screens/user/UserCommentScreen/UserCommentScreen.tsx
  src/screens/userEvent/UserTicketScreen/UserTicketScreen.tsx
Labels: 🐛 bug, 💅 design

#118 🔀 애플로그인 수정
  src/navigators/AuthorizeNavigator.tsx
  src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.tsx
  src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
  src/types/join.ts
Labels: ✨ feat

#120 🔀 안드로이드에서 앱다운시 앱이름이 영어로 보이는 이슈
  android/app/src/main/res/values-ko/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: 🐛 bug

#122 🔀 ios 상태바 글자 흰색, 가로모드 미지원
  App.tsx
  ios/OpenOff/Info.plist
Labels: 🐛 bug, 💅 design

#128 ci: 배포 버전 관리
  .github/pull_request_template.md
  .versionrc.js
  README.md
  ios/OpenOff.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 👷 ci

#132 improvement: 카테고리명 및 카테고리 순서 변경
  src/apis/interest.ts
  src/apis/test.ts
  src/components/authorize/buttons/FieldButton/FieldButton.tsx
  src/components/authorize/groups/FieldButtonGroup/FieldButtonGroup.tsx
  src/components/eventMap/buttons/MapFieldButton/MapFieldButton.tsx
  src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
  src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.tsx
  src/components/home/buttons/CategoryButton/CategoryButton.style.ts
  src/components/home/buttons/CategoryButton/CategoryButton.tsx
  src/components/home/buttons/TopFieldButton/TopFieldButton.tsx
  src/components/home/cards/AlertCard/AlertCard.tsx
  src/components/home/cards/EventRowCard/EventRowCard.tsx
  src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.style.ts
  src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.tsx
  src/components/home/groups/TopFieldButtonGroup/TopFieldButtonGroup.tsx
  src/components/openEvent/forms/Field/Field.tsx
  src/components/userEvent/participant/CategorySelector/CategorySelector.tsx
  src/components/userEvent/participant/TicketList/TicketList.tsx
  src/constants/alertCode.ts
  src/constants/interest.ts
  src/constants/openEvent/fieldData.ts
  src/constants/queries/resetQueryKey.ts
  src/constants/queryKeys.ts
  src/constants/userEvent/participant/fieldData.ts
  src/data/interestFieldData.json
  src/data/lists/fieldData.ts
  src/hooks/authorize/useInterestField.ts
  src/hooks/eventMap/useEventMapSelector.tsx
  src/hooks/interest/useInterestFields.ts
  src/hooks/openEvent/useField.ts
  src/hooks/queries/event.ts
  src/hooks/queries/interest.ts
  src/hooks/queries/ledger.ts
  src/models/alert/AlertType.ts
  src/models/event/request/CreateNewEventRequestDto.ts
  src/models/event/request/EventFieldListRequestDto.ts
  src/models/event/request/EventSearchRequestDto.ts
  src/models/event/response/MyBookmarkEventResponseDto.ts
  src/models/field/request/AddInterestRequestDto.ts
  src/models/interest/response/InterestInfoResponseDto.ts
  src/models/ledger/request/ApplicationInfoRequestDto.ts
  src/models/ledger/request/HostEventInfoRequestDto.ts
  src/models/ledger/response/ApplicationInfoResponseDto.ts
  src/models/ledger/response/HostEventInfoResponseDto.ts
  src/models/user/response/UserTotalInfoResponseDto.ts
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/home/CategoryEventScreen/CategoryEventScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/user/UserInterestResetScreen/UserInterestResetScreen.tsx
  src/screens/user/UserScreen/UserScreen.tsx
  src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
  src/types/event.ts
  src/types/event/filedDataType.ts
  src/types/icon.ts
  src/types/interest.ts
  src/types/join.ts
  src/types/openEvent/EventForm.ts
Labels: 🌈 enhancement

#126 fix: 지도화면에서 나온 QA 진행
  src/assets/icons/IconMyCoordinate.svg
  src/assets/images/eventCoordinate.png
  src/components/eventMap/buttons/CurrentFieldFindButton/CurrentFieldFindButton.style.ts
  src/components/eventMap/buttons/CurrentFieldFindButton/CurrentFieldFindButton.tsx
  src/components/eventMap/buttons/MapFieldButton/MapFieldButton.style.ts
  src/components/eventMap/buttons/MapFieldButton/MapFieldButton.tsx
  src/components/eventMap/buttons/MyCoordinateButton/MyCoordinateButton.style.ts
  src/components/eventMap/buttons/MyCoordinateButton/MyCoordinateButton.tsx
  src/components/eventMap/buttons/SelectBoxButton/SelectBoxButton.style.ts
  src/components/eventMap/buttons/SelectBoxButton/SelectBoxButton.tsx
  src/components/eventMap/buttons/SelectDetailButton/SelectDetailButton.style.ts
  src/components/eventMap/buttons/SelectDetailButton/SelectDetailButton.tsx
  src/components/eventMap/cards/CalendarCard/CalendarCard.tsx
  src/components/eventMap/cards/MapEventCard/MapEventCard.style.ts
  src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
  src/components/eventMap/dialogs/SortDialog/SortDialog.style.ts
  src/components/eventMap/dialogs/SortDialog/SortDialog.tsx
  src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.style.ts
  src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.tsx
  src/components/eventMap/groups/SelectBoxGroup/SelectBoxGroup.style.ts
  src/components/eventMap/groups/SelectDetailGroup/SelectDetailGroup.style.ts
  src/components/eventMap/groups/SingleOptionGroup/SingleOptionGroup.style.ts
  src/components/eventMap/inputs/EventSearchInput/EventSearchInput.style.ts
  src/components/eventMap/inputs/EventSearchInput/EventSearchInput.tsx
  src/components/eventMap/maps/CurrentMarker/CurrentMarker.tsx
  src/components/eventMap/maps/EventMarker/EventMarker.tsx
  src/components/eventMap/selectboxes/SelectDetailBox/SelectDetailBox.style.ts
  src/components/eventMap/selectboxes/SelectDetailBox/SelectDetailBox.tsx
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.style.ts
  src/components/eventMap/sheets/MapBottomSheet/MapBottomSheet.tsx
  src/components/home/buttons/BookmarkButton/BookmarkButton.style.ts
  src/components/suspense/skeleton/MapEventCardSkeleton/MapEventCardSkeleton.style.ts
  src/hooks/eventMap/useEventListFormatter.tsx
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
Labels: 🐛 bug, 🫧refactor, 💅 design

#135 feat: 명단 검색 기능 추가
  src/components/userEvent/host/LedgerSearchBar/LedgerSearchBar.style.ts
  src/components/userEvent/host/LedgerSearchBar/LedgerSearchBar.tsx
  src/components/userEvent/host/index.ts
  src/hooks/queries/ledger.ts
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
Labels: ✨ feat

#137 feat: refetch 기능 강화
  src/components/eventDetail/atoms/comments/CommentInput/CommentInput.tsx
  src/components/eventMap/groups/SelectBoxGroup/SelectBoxGroup.tsx
  src/components/eventMap/groups/SelectDetailGroup/SelectDetailGroup.tsx
  src/components/home/buttons/BookmarkButton/BookmarkButton.tsx
  src/components/suspense/skeleton/EventCardSkeleton/EventCardSkeleton.tsx
  src/components/user/buttons/UserProfileImageButton/UserProfileImageButton.tsx
  src/components/userEvent/host/StaffList/StaffList.tsx
  src/components/userEvent/host/UserCard/UserCard.tsx
  src/components/userEvent/host/UserHeader/UserHeader.tsx
  src/constants/queries/queryKeys.ts
  src/constants/queries/resetQueryKey.ts
  src/hooks/app/useAppState.ts
  src/hooks/app/useRefetchOnFocus.ts
  src/hooks/eventMap/useMapCoordinateInfo.ts
  src/hooks/queries/banner.ts
  src/hooks/queries/bookmark.ts
  src/hooks/queries/comment.ts
  src/hooks/queries/event.ts
  src/hooks/queries/interest.ts
  src/hooks/queries/ledger.ts
  src/hooks/queries/user.ts
  src/navigators/Navigator.tsx
  src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
  src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
  src/screens/events/EventCommentScreen/EventCommentScreen.tsx
  src/screens/events/EventDetailScreen/EventDetailScreen.tsx
  src/screens/home/HomeScreen/HomeScreen.tsx
  src/screens/home/OpenEventScreen/OpenEventScreen.tsx
  src/screens/user/UserInterestResetScreen/UserInterestResetScreen.tsx
  src/screens/userEvent/HostConsoleScreen/HostConsoleScreen.tsx
  src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
  src/screens/userEvent/HostQRScanScreen/HostQRScanScreen.tsx
  src/services/fcm.ts
Labels: ✨ feat
